apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-python-deploy

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: matveyplevako/app_python
          ports:
            - containerPort: 8000
